package com.fourverr.api.model;

public enum TipoProducto {
    SERVICIO_GIG,
    CURSO_DIGITAL,
    RECURSO_DESCARGABLE,
    SUSCRIPCION,
    PRODUCTO_FISICO,
    CONSULTORIA,
    DISENO_GRAFICO,
    DESARROLLO_WEB,
    MARKETING_DIGITAL,
    MUSICA_AUDIO
}
